# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forky < Formula
  desc ""
  homepage "https://github.com/thetnaingtn/forky"
  version "0.4.3"

  on_macos do
    url "https://github.com/thetnaingtn/forky/releases/download/v0.4.3/forky_0.4.3_darwin_all.tar.gz"
    sha256 "8e4998a204b7c400e0345f688f4049ce275da6977f5edc26456f7141a33373dd"

    def install
      bin.install "forky"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thetnaingtn/forky/releases/download/v0.4.3/forky_0.4.3_linux_arm64.tar.gz"
      sha256 "2b66145b2fc82fdb3d8380c218ee1cc0392349635d338d773eb7d83321b64880"

      def install
        bin.install "forky"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/thetnaingtn/forky/releases/download/v0.4.3/forky_0.4.3_linux_amd64.tar.gz"
      sha256 "2966f0163b333e9236f9b5240be5013f79ec9c0cd451011fdb88b9934329ab30"

      def install
        bin.install "forky"
      end
    end
  end
end
