# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forky < Formula
  desc ""
  homepage "https://github.com/thetnaingtn/forky"
  version "0.6.4"

  on_macos do
    url "https://github.com/thetnaingtn/forky/releases/download/v0.6.4/forky_0.6.4_darwin_all.tar.gz"
    sha256 "3a5a88d78a32969daeb70163a721d5f147371b683fb7d95834f38c45b65fb7e2"

    def install
      bin.install "forky"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thetnaingtn/forky/releases/download/v0.6.4/forky_0.6.4_linux_arm64.tar.gz"
      sha256 "6aacebdb62c27e43f46aa627fd05f85e931544ca27e91f417d3103561ce1c630"

      def install
        bin.install "forky"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/thetnaingtn/forky/releases/download/v0.6.4/forky_0.6.4_linux_amd64.tar.gz"
      sha256 "ff1330010729d256406f8c63d3cad6206de6c7000f963ce19ef860e18053795e"

      def install
        bin.install "forky"
      end
    end
  end
end
